spring:
  application:
    name: discoveryserver

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: false
    fetchRegistry: false