services:
  address-service:
    build:
      context: ./addressservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8090:8090"
    restart: on-failure
    networks:
      - common
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    volumes:
      - ~/.m2:/root/.m2
  product-service:
    build: ./productservice
    ports:
      - "8084:8084"
    restart: on-failure # hata aldığında çalışana kadar rest
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common
  customer-service:
    build:
      context: ./customerservice
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8087:8087"
    restart: on-failure
    networks:
      - common
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    volumes:
      - ~/.m2:/root/.m2
  cart-service:
    build: ./cartservice
    ports:
      - "8082:8082"
    restart: on-failure # hata aldığında çalışana kadar rest
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common
  order-service:
    build: ./orderservice
    ports:
      - "8083:8083"
    restart: on-failure # hata aldığında çalışana kadar rest
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common
  config-server:
    build: ./configserver
    ports:
      - "8079:8079"
    networks:
      - common
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8888:8888"
    restart: on-failure
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common

  identity-service:
    build: ./identityservice
    ports:
      - "8086:8086"
    restart: on-failure
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common
  gateway-server:
    build: ./gatewayserver
    ports:
      - "8080:8080"
    restart: on-failure # her hata aldığında restart et
    # restart : unless-stopped kullanıcı dışında konteyner durdu ise  restart et
    # alway kullanıcı dahil herhangi bir şekilde durdu ise
    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common
  mongodb:
    image: mongo
    ports:
      - "27017:27017"


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

volumes:
  postgresql-volume: #dosyada ki nickname
    name: postgresql-volume #klasör ismi

networks:
  common:
    driver: bridge
