package com.tcellpair3.customerservice.core.mernis;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 7514DA398BDE186C83FF2FCF62343D2D30B722E6C1FE5D70086D8F599FE5600238108EF4A15D8376A5246B28AB17D62381E279BBD89E4E3F3C1DD24EDBF7667B
//------------------------------------------------------------------------
import java.util.Date;


public interface IRKDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}